---
#######################################################################################
#A default configuration that will be loaded for all jupyter books
#Users are expected to override these values in their own `_config.yml` file.
#This is also the "master list" of all allowed keys and values.
#######################################################################################
#Book settings
title: 诱人之路 #The title of the book. Will be placed in the left navbar.
author: 诱导之道社区 #The author of the book
copyright: "2020-2021" #Copyright year to be placed in the footer
logo: "./figures/logo.jpg" #A path to the book logo
email: "theturingway@gmail.com"
exclude_patterns:  #A list of patterns to *skip* in execution (for example a notebook that takes a really long time)
  - "私信"
#######################################################################################
#HTML-specific settings
html:
  favicon: "./figures/logo/favicon-32x32.png" #A path to a favicon image
  navbar_number_sections: false #Add a number to each section in your left navbar
  google_analytics_id: "UA-167881009-1" #A GA id that can be used to track book views.
  home_page_in_navbar: true #Whether to include your home page in the left Navigation Bar
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  baseurl: "https://the-turing-way.netlify.com" #The base URL where your book will be hosted. Used for creating image previews and social links. for example: https://mypage.com/mybook/
  extra_navbar: 访问我们的 <a href="https://github.com/alan-turing-institute/the-turing-way">GitHub 存储库</a> <div>这本书由 <a href="https://jupyterbook.org">Jupyter 书</a></div>
  comments:
    hypothesis: true
#######################################################################################
#Launch button settings
launch_buttons:
  notebook_interface: "经典" #The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org" #The URL of the BinderHub (for example, https://mybinder.org)
  jupyterhub_url: "" #The URL of the JupyterHub (for example, https://datahub.berkeley.edu)
  thebelab: false #Add a thebelab button to pages (requires the repository to run on Binder)
repository:
  url: https://github.com/alan-turing-institute/the-turing-way
  path_to_book: "书/网站" #A path to your book's folder, relative to the repository root.
  branch: 主要的
#######################################################################################
#Advanced and power-user settings
sphinx:
  extra_extensions:  #A list of extra extensions to load by Sphinx.
  config:  #key-value pairs to directly over-ride the Sphinx configuration
    language: 中
bibtex_bibfiles:
  - _bibliography/reference.bb
